language = {}

LANG = 'ru'

language['en'] = {
	'precense_servers' : 'servers',
	'precense_users' : 'users',
}

language['ru'] = {
	'precense_servers' : 'сервера',
	'precense_users' : 'человек',
	'game_price' : 'Цена игры',
	'discount_ended' : 'Акция закончилась',
	'not_ru_akk' : '(Не для RU аккаунта)',
	'game_link' : 'Ссылка на раздачу',
	'discount_will_ended' : 'Акция заканчивается',
	'no_channel' : 'Канал не установлен',
	'no_role' : 'Роль не установлена',
	'no_message_changes' : 'Без изменений',
	'message_changes_delete' : 'Сообщения будут удаляться',
	'message_changes_edit' : 'Сообщения будут изменяться',
	'bot_started' : 'Бот запущен',
	'bot_stoped' : 'Бот остановлен',
	'settings' : 'Настройки бота',
	'current_channel' : 'Канал для раздач',
	'current_role' : 'Роль для раздач',
	'current_mode' : 'Режим для сообщений',
	'bot_status' : 'Статус бота',
	'reset_submit_modal' : 'Для сброса настроек бота введите \'SUBMIT\'',
	'reset_submit' : 'Сброс настроек бота',
	'reset_canceled' : 'Ошибка : сброс настроек бота отменён!',
	'reset_successful' : 'Сброс настроек успешно произведён!',
	'reset_confirm' : 'Подтвердить',
	'return_to_settings' : 'Вернуться в меню настроек',
	'choose_channel' : 'Выберите текстовый канал',
	'settings_channel' : 'Настройки канала',
	'channel' : 'сообщества',
	'current_channel_for' : 'Текущий канал раздач для',
	'channel_not_exists' : 'Ошибка : такой канал больше не существует.',
	'last_channel' : 'Прошлый канал',
	'none_role' : 'Нет выбранной роли',
	'choose_role' : 'Выберите роль для упоминания',
	'settings_role' : 'Настройки роли',
	'current_role_for' : 'Текущая роль для упоминания',
	'role_not_exists' : 'Ошибка : такой роли больше не существует',
	'last_role' : 'Прошлая роль',
	'delete_message' : 'Удалить сообщение',
	'edit_message' : 'Изменить сообщение',
	'none_message' : 'Ничего не делать с сообщением',
	'choose_message' : 'Выберите режим, что произойдёт с сообщением после окончания акции',
	'settings_message' : 'Настройки режима, что произойдёт с сообщением',
	'current_message_for' : 'Текущий режим, что произойдёт с сообщением',
	'last_message' : 'Прошлый режим',
	'bot_start' : 'Запустить бота',
	'bot_stop' : 'Остановить бота',
	'channel_setup' : 'Выбрать канал',
	'no_channels_guild' : 'Нет доступных текстовых каналов в этом сообществе',
	'message_setup' : 'Выбрать режим, для сообщений',
	'role_setup' : 'Выбрать роль',
	'no_roles_guild' : 'Нет доступных ролей в этом сообществе',
	'reset' : 'Сбросить настройки',
	'message_reset' : 'Вы точно уверены, что хотите сбросить ВСЕ настройки бота в этом сообществе?',
	'fix_message_editor' : 'Изменение сообщения',
	'fix_message_editor_error' : 'Ошибка : ключ не распознан, возможно в графе \'key\' вы прописали что-то иное, а не ru или not_ru',
	'fix_message_apply' : 'Подтвердить изменения',
	'fix_message_edit_successful' : 'Изменение сообщения : успешно!',
	'fix_message_discard' : 'Отменить изменения',
	'fix_message_edit_discard' : 'Изменение сообщения : отменено!',
	'fix_message_how_view' : 'Как будет выглядеть изменённое сообщение',
	'fix_message_delete_modal' : 'Для удаления сообщения введите \'SUBMIT\'',
	'fix_message_delete_submit' : 'Подтвердить удаление',
	'fix_message_delete_error' : 'Ошибка : удаление сообщения отменено!',
	'fix_message_delete_successful' : 'Сообщение удалено!',
	'fix_message_choose' : 'Выберите сообщение',
	'fix_message_message_not_exists' : 'Ошибка : это сообщение больше не существует!',
	'fix_message_change_message' : 'Изменить сообщение',
	'fix_message_modal_title' : 'Название игры',
	'fix_message_modal_description' : 'Описание игры',
	'fix_message_modal_url' : 'Ссылка на игру в Epic Games Store',
	'fix_message_modal_price' : 'Цена на игру',
	'fix_message_modal_key' : 'Доступ раздачи в РФ, \'ru\' или \'not_ru\'',
	'fix_message_button_delete' : 'Удалить сообщение',
	'fix_message_how_view_now' : 'Как сейчас выглядит сообщение',
	'fix_message_no_messages' : 'Нет сообщений, которые можно изменить/удалить',
	'send_to_channel_choose' : 'Выберите канал, куда перебросить пользователя с ником',
	'send_to_channel_sorry' : 'Извините',
	'send_to_channel_no_voice' : 'должен находиться в голосовом канале',
	'send_to_channel_will_be_sent' : 'будет переброшен в',
	'send_to_channel_channel' : '',
	'send_to_channel_check_all' : 'Посмотреть все голосовые каналы',
	'give_permissions_describe' : 'True - выдать полномочия для управления ботом, False - забрать их',
	'give_permissions_all_ready' : 'Всё готово',
	'give_permissions_new_status' : 'Получает новый статус',
	'give_permissions_error_bot' : 'Ошибка : нельзя наделить или забрать полномочия бота для использования UniBot',
	'dont_have_permissions' : 'У вас недостаточно полномочий для использования этой команды',
	'something_went_wrong' : 'Упс... Произошла ошибка! Если у вас есть возможность, напишите разработчику, желательно опишите, при каких обстоятельствах произошла ошибка.'
}